-- MySQL Script generated by MySQL Workbench
-- Ср 28 сен 2016 12:04:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yo_db` DEFAULT CHARACTER SET utf8 ;
USE `yo_db` ;

-- -----------------------------------------------------
-- Table `yo_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_fullName` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_status` VARCHAR(45) NOT NULL DEFAULT 'С удовольствием покажу вам свою локацию',
  `user_level` INT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `photo_src` VARCHAR(255) NOT NULL,
  `photo_alt` VARCHAR(20) NOT NULL,
  `photo_type` VARCHAR(40) NOT NULL,
  `photo_user_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `photo_user_id`),
  INDEX `fk_photos_users1_idx` (`photo_user_id` ASC),
  CONSTRAINT `fk_photos_users1`
    FOREIGN KEY (`photo_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`lu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`lu` (
  `lu_language_id` INT NOT NULL,
  `lu_user_id` INT NOT NULL,
  `lu_lang_lavel` INT(2) NOT NULL,
  PRIMARY KEY (`lu_language_id`, `lu_user_id`),
  INDEX `fk_lang_user_users1_idx` (`lu_user_id` ASC),
  CONSTRAINT `fk_lang_user_lang1`
    FOREIGN KEY (`lu_language_id`)
    REFERENCES `yo_db`.`language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lang_user_users1`
    FOREIGN KEY (`lu_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `activity_name` CHAR(45) NOT NULL,
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`au`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`au` (
  `au_activity_id` INT NOT NULL,
  `au_user_id` INT NOT NULL,
  PRIMARY KEY (`au_activity_id`, `au_user_id`),
  INDEX `fk_intrestings_user_users1_idx` (`au_user_id` ASC),
  CONSTRAINT `fk_intrestings_user_intrestings1`
    FOREIGN KEY (`au_activity_id`)
    REFERENCES `yo_db`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intrestings_user_users1`
    FOREIGN KEY (`au_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`msg` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `msg_user_to` INT NOT NULL,
  `msg_user_from` INT NOT NULL,
  `msg_text` TEXT NOT NULL,
  `msg_date` DATE NOT NULL,
  PRIMARY KEY (`msg_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`online`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`online` (
  `online_date` DATE NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`),
  INDEX `fk_online_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_online_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `location_country` VARCHAR(45) NOT NULL,
  `location_city` VARCHAR(45) NOT NULL,
  `location_photo` VARCHAR(255) NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`location_id`, `user_user_id`),
  INDEX `fk_location_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_location_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yo_db`.`travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yo_db`.`travel` (
  `travel_id` INT NOT NULL,
  `travel_guide_id` INT NOT NULL,
  `travel_date` DATE NOT NULL,
  `travel_description` VARCHAR(255) NOT NULL,
  `travel_user_id` INT NOT NULL,
  PRIMARY KEY (`travel_id`, `travel_user_id`),
  INDEX `fk_travel_user1_idx` (`travel_user_id` ASC),
  CONSTRAINT `fk_travel_user1`
    FOREIGN KEY (`travel_user_id`)
    REFERENCES `yo_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
